// Original English-language practice content, written at CEFR B1 level —
// the level generally required to demonstrate English proficiency as part
// of a UK settlement or citizenship application. Not tied to, or copied
// from, any specific exam board's test material.

const EN_GROUPS = [
  { id: 1, title: "Grammar" },
  { id: 2, title: "Vocabulary" },
  { id: 3, title: "Reading comprehension" }
];

const EN_QUESTIONS = [
/* ===================== Grammar ===================== */
{group:1,q:"She ___ to the shop every Saturday morning.",opts:["go","goes","going","gone"],correct:1,ex:"With he/she/it in the present simple, we add -s: 'goes'."},
{group:1,q:"They ___ dinner when I arrived at their house.",opts:["have","were having","has","had have"],correct:1,ex:"Past continuous ('were having') describes an action in progress when another event happened."},
{group:1,q:"I have lived in this city ___ five years.",opts:["since","for","from","during"],correct:1,ex:"'For' is used with a length of time; 'since' is used with a starting point in time."},
{group:1,q:"If it rains tomorrow, we ___ the picnic.",opts:["cancel","cancelled","will cancel","cancelling"],correct:2,ex:"First conditional: if + present simple, ... will + base verb."},
{group:1,q:"He asked me where ___.",opts:["do I live","I live","did I lived","I lived"],correct:3,ex:"In reported questions, the word order becomes statement order and the tense usually shifts back: 'I lived'."},
{group:1,q:"She has always been interested ___ music.",opts:["on","at","in","for"],correct:2,ex:"'Interested in' is the correct preposition combination."},
{group:1,q:"She's the woman ___ helped me find my way yesterday.",opts:["who","which","whose","whom"],correct:0,ex:"'Who' is used as the relative pronoun for people acting as the subject of the clause."},
{group:1,q:"I ___ my keys. Can you help me look for them?",opts:["lose","lost","have lost","losing"],correct:2,ex:"Present perfect ('have lost') is used for a past action with a result that matters now."},
{group:1,q:"___ apple a day is said to keep the doctor away.",opts:["A","An","The","Some"],correct:1,ex:"'An' is used before words that start with a vowel sound, such as 'apple'."},
{group:1,q:"By next year, I ___ in this flat for ten years.",opts:["will live","will have lived","have lived","was living"],correct:1,ex:"Future perfect ('will have lived') describes something that will be completed by a future point in time."},
{group:1,q:"You ___ smoke inside a hospital building — it's against the rules.",opts:["don't have to","mustn't","might not","needn't"],correct:1,ex:"'Mustn't' expresses that something is prohibited or not allowed."},
{group:1,q:"This flat is much ___ than my old one.",opts:["big","bigger","biggest","more big"],correct:1,ex:"The comparative form of 'big' is 'bigger'."},
{group:1,q:"I wish I ___ more free time these days.",opts:["have","had","will have","having"],correct:1,ex:"After 'I wish', we use the past simple to talk about a present situation we would like to be different."},
{group:1,q:"The letter ___ yesterday afternoon.",opts:["sent","was sent","has sent","is sending"],correct:1,ex:"Passive voice, past simple: 'was sent'."},
{group:1,q:"He told me that he ___ tired after the long shift.",opts:["is","was","be","being"],correct:1,ex:"In reported speech, present tense usually shifts back to past tense: 'was tired'."},
{group:1,q:"Neither of the answers ___ correct.",opts:["are","is","were","be"],correct:1,ex:"'Neither of' is followed by a singular verb in formal English: 'is'."},
{group:1,q:"She has been working at that company ___ 2019.",opts:["for","since","during","by"],correct:1,ex:"'Since' is used with a specific starting point, such as a year."},
{group:1,q:"If I ___ you, I would apologise straight away.",opts:["am","was","were","be"],correct:2,ex:"In the second conditional, 'were' is used for all subjects, including 'I', in formal English."},

/* ===================== Vocabulary ===================== */
{group:2,q:"What is the word for the place where you go to buy medicine?",opts:["Pharmacy","Bakery","Surgery","Clinic only"],correct:0,ex:"A pharmacy (also called a chemist) is where you collect prescriptions and buy medicine."},
{group:2,q:"An 'appointment' most closely means:",opts:["A planned meeting at a fixed time","A type of medicine","A place to live","A monthly bill"],correct:0,ex:"An appointment is an arrangement to meet or see someone at a set time, e.g. a doctor's appointment."},
{group:2,q:"Which word means the opposite of 'arrive'?",opts:["Enter","Depart","Return","Stay"],correct:1,ex:"'Depart' means to leave, the opposite of 'arrive'."},
{group:2,q:"If something is 'affordable', it is:",opts:["Very expensive","Not too expensive for most people","Free of charge","Difficult to find"],correct:1,ex:"'Affordable' describes something priced within most people's means."},
{group:2,q:"In the UK, a 'GP' usually refers to:",opts:["A family doctor","A government office","A type of medicine","A hospital department"],correct:0,ex:"GP stands for General Practitioner — a family doctor usually seen for everyday health concerns."},
{group:2,q:"To 'commute' means to:",opts:["Travel regularly to and from work","Apply for a job","Take a holiday","Change your job"],correct:0,ex:"Commuting is the regular journey between home and your workplace."},
{group:2,q:"Choose the best word: \"Could you ___ the volume, please? It's too loud.\"",opts:["turn down","turn up","turn on","turn over"],correct:0,ex:"'Turn down' means to reduce the level, such as volume."},
{group:2,q:"A 'tenant' is:",opts:["Someone who rents a property","Someone who owns a property","A type of legal document","A government official"],correct:0,ex:"A tenant is a person who rents a home or other property from a landlord."},
{group:2,q:"'Utility bills' usually refers to charges for:",opts:["Gas, electricity, and water","Clothes and shoes","Restaurant meals","Public transport tickets"],correct:0,ex:"Utility bills cover essential household services such as gas, electricity, and water."},
{group:2,q:"Which word means 'to book something in advance'?",opts:["Reserve","Refuse","Return","Repair"],correct:0,ex:"'Reserve' means to arrange to have something kept for you, such as a table or a ticket."},
{group:2,q:"\"I'm on a tight budget\" means:",opts:["I don't have much money to spend","I have plenty of spare time","I am very busy at work","I dislike my job"],correct:0,ex:"A 'tight budget' means limited money available for spending."},
{group:2,q:"'Overtime' refers to:",opts:["Extra hours worked beyond normal working hours","A type of holiday leave","A late train service","A lunch break"],correct:0,ex:"Overtime is extra time worked in a job beyond the standard hours, often paid at a higher rate."},
{group:2,q:"Which word is the best synonym for 'essential'?",opts:["Necessary","Optional","Expensive","Unusual"],correct:0,ex:"'Essential' means absolutely necessary."},
{group:2,q:"If a job is 'redundant', it usually means:",opts:["It is no longer needed and has been cut","It has been promoted","It pays more money","It has become part-time"],correct:0,ex:"'Redundant' describes a job position that has been removed, often for business reasons."},
{group:2,q:"A 'landlord' is:",opts:["The owner who rents out a property","A person who cleans houses","A government housing officer","A type of tenancy agreement"],correct:0,ex:"A landlord owns a property and rents it out to tenants."},
{group:2,q:"\"I'm running late\" means:",opts:["I will arrive after the expected time","I am exercising outdoors","I have already arrived","I have cancelled my plans"],correct:0,ex:"'Running late' means you will not arrive on time."},
{group:2,q:"'Reliable' most closely means:",opts:["Can be trusted to work or behave consistently well","Very expensive","Difficult to understand","Brand new"],correct:0,ex:"'Reliable' describes something or someone that consistently performs well and can be trusted."},
{group:2,q:"A 'refund' is:",opts:["Money given back to a customer","An extra charge added to a bill","A type of loan","A discount on a future purchase"],correct:0,ex:"A refund is money returned to a customer, often after returning goods."},

/* ===================== Reading comprehension ===================== */
{group:3,passage:"To register with a doctor's surgery in the UK, you usually need to fill in a form and provide proof of address, such as a utility bill. Once registered, you can book appointments by phone or online. If it is not an emergency, you may have to wait a few days to see a doctor.",q:"What proof is usually needed to register with a GP surgery?",opts:["A passport photo only","Proof of address, such as a utility bill","A letter from an employer","A bank statement only"],correct:1,ex:"The passage states that proof of address, such as a utility bill, is usually required."},
{group:3,passage:"To register with a doctor's surgery in the UK, you usually need to fill in a form and provide proof of address, such as a utility bill. Once registered, you can book appointments by phone or online. If it is not an emergency, you may have to wait a few days to see a doctor.",q:"How can patients book appointments, according to the passage?",opts:["Only in person","By phone or online","By letter only","Through a mobile app only"],correct:1,ex:"The passage says appointments can be booked by phone or online."},
{group:3,passage:"To register with a doctor's surgery in the UK, you usually need to fill in a form and provide proof of address, such as a utility bill. Once registered, you can book appointments by phone or online. If it is not an emergency, you may have to wait a few days to see a doctor.",q:"What might happen if a visit is not an emergency?",opts:["The patient is refused an appointment","The patient may have to wait a few days","The patient must pay extra","The patient is sent to hospital"],correct:1,ex:"The passage explains that non-emergency visits may involve waiting a few days."},

{group:3,passage:"Before renting a flat, tenants are usually asked to pay a deposit, which is protected in a government-approved scheme. The landlord must give tenants a written tenancy agreement explaining the rules, such as the monthly rent and the notice period required to end the tenancy.",q:"What happens to the deposit a tenant pays?",opts:["It is kept by the landlord in cash","It is protected in a government-approved scheme","It is returned immediately","It is used to pay the first month's rent"],correct:1,ex:"The passage states the deposit is protected in a government-approved scheme."},
{group:3,passage:"Before renting a flat, tenants are usually asked to pay a deposit, which is protected in a government-approved scheme. The landlord must give tenants a written tenancy agreement explaining the rules, such as the monthly rent and the notice period required to end the tenancy.",q:"What must a landlord provide to tenants?",opts:["A written tenancy agreement","A free set of furniture","A parking space","A monthly inspection report"],correct:0,ex:"The passage says the landlord must give tenants a written tenancy agreement."},
{group:3,passage:"Before renting a flat, tenants are usually asked to pay a deposit, which is protected in a government-approved scheme. The landlord must give tenants a written tenancy agreement explaining the rules, such as the monthly rent and the notice period required to end the tenancy.",q:"What does the tenancy agreement usually explain?",opts:["Rules such as rent and notice period","The tenant's employment history","The landlord's personal finances","Local school catchment areas"],correct:0,ex:"The passage says the agreement explains rules such as the rent and notice period."},

{group:3,passage:"Most cities in the UK have buses and trains that run regularly during the day, with fewer services at night. Many people use a contactless card or a travel pass to pay for journeys, which is often cheaper than buying a single paper ticket each time.",q:"When are public transport services generally less frequent?",opts:["Early morning","At night","At midday","On weekends only"],correct:1,ex:"The passage states there are fewer services at night."},
{group:3,passage:"Most cities in the UK have buses and trains that run regularly during the day, with fewer services at night. Many people use a contactless card or a travel pass to pay for journeys, which is often cheaper than buying a single paper ticket each time.",q:"What is often cheaper than a single paper ticket?",opts:["Paying the driver in cash","A contactless card or travel pass","Booking a taxi instead","Walking instead of using transport"],correct:1,ex:"The passage says using a contactless card or travel pass is often cheaper."},
{group:3,passage:"Most cities in the UK have buses and trains that run regularly during the day, with fewer services at night. Many people use a contactless card or a travel pass to pay for journeys, which is often cheaper than buying a single paper ticket each time.",q:"Which types of transport does the passage mention?",opts:["Buses and trains","Only trains","Only buses","Bicycles and ferries"],correct:0,ex:"The passage mentions both buses and trains."},

{group:3,passage:"Before a job interview, it is a good idea to research the company and prepare answers to common questions, such as why you want the role. Arriving a few minutes early and dressing appropriately for the workplace also creates a good first impression.",q:"What should a candidate research before an interview?",opts:["The interviewer's personal life","The company","Competing candidates","Public transport delays only"],correct:1,ex:"The passage advises researching the company before an interview."},
{group:3,passage:"Before a job interview, it is a good idea to research the company and prepare answers to common questions, such as why you want the role. Arriving a few minutes early and dressing appropriately for the workplace also creates a good first impression.",q:"What is one common interview question mentioned in the passage?",opts:["Why you want the role","What your salary expectations are","Where you went to school","What your hobbies are"],correct:0,ex:"The passage gives 'why you want the role' as an example of a common question."},
{group:3,passage:"Before a job interview, it is a good idea to research the company and prepare answers to common questions, such as why you want the role. Arriving a few minutes early and dressing appropriately for the workplace also creates a good first impression.",q:"According to the passage, what helps create a good first impression?",opts:["Arriving early and dressing appropriately","Arriving exactly on time only","Bringing a friend along","Avoiding eye contact"],correct:0,ex:"The passage says arriving a few minutes early and dressing appropriately creates a good impression."},

{group:3,passage:"To open a bank account in the UK, you usually need to show identification, such as a passport, and proof of address. Most banks offer online and mobile banking, allowing customers to check their balance and pay bills without visiting a branch.",q:"What type of identification might be needed to open a bank account?",opts:["A passport","A library card only","A gym membership","A social media profile"],correct:0,ex:"The passage gives a passport as an example of identification that might be needed."},
{group:3,passage:"To open a bank account in the UK, you usually need to show identification, such as a passport, and proof of address. Most banks offer online and mobile banking, allowing customers to check their balance and pay bills without visiting a branch.",q:"What else is usually required, alongside identification?",opts:["Proof of address","A university degree","A second passport","A letter from a landlord's solicitor"],correct:0,ex:"The passage states proof of address is also usually required."},
{group:3,passage:"To open a bank account in the UK, you usually need to show identification, such as a passport, and proof of address. Most banks offer online and mobile banking, allowing customers to check their balance and pay bills without visiting a branch.",q:"What can customers do using mobile banking, according to the passage?",opts:["Check their balance and pay bills","Only view adverts","Apply for a passport","Book doctor's appointments"],correct:0,ex:"The passage says mobile banking lets customers check their balance and pay bills."},

{group:3,passage:"The local community centre holds weekly events, including English conversation classes and a coffee morning for older residents. Entry to most events is free, though a small donation is welcomed to help cover the cost of refreshments.",q:"What classes are held weekly at the community centre?",opts:["English conversation classes","Cooking classes","Driving lessons","Computer repair classes"],correct:0,ex:"The passage mentions weekly English conversation classes."},
{group:3,passage:"The local community centre holds weekly events, including English conversation classes and a coffee morning for older residents. Entry to most events is free, though a small donation is welcomed to help cover the cost of refreshments.",q:"Who is the coffee morning mainly aimed at?",opts:["Older residents","Young children only","New employees","Local business owners"],correct:0,ex:"The passage states the coffee morning is for older residents."},
{group:3,passage:"The local community centre holds weekly events, including English conversation classes and a coffee morning for older residents. Entry to most events is free, though a small donation is welcomed to help cover the cost of refreshments.",q:"Is there usually a charge to attend these events?",opts:["Entry is mostly free, with donations welcomed","Entry always costs a fixed fee","Only members can attend","Attendance requires a formal application"],correct:0,ex:"The passage says entry is mostly free, though a small donation is welcomed."}
];
